version: '3.5'
services:
    database:
        image: mongo:4.4.5
        ports:
            - 27003:27017
    # backend:
    #     build: ./backend
    #     ports:
    #         - 6587:6587
    #     depends_on:
    #         - database
    # frontend:
    #     build: ./frontend
    #     ports: 
    #         - 80:80
    #     depends_on:
    #         - backend
