version: '3.5'
services:
    database:
        image: mongo:4.4.5
        ports:
            - 27003:27017
    backend:
        build: ./backend
        ports:
            - 6587:6587
        depends_on:
            - database
    # zorgmedewerker_app:
    #     build: ./zorgmedewerker-app
    #     ports: 
    #         - 6588:6588
    #     depends_on:
    #         - backend
