version: '3.5'
services:
    database:
        image: mongo:4.4.5
        ports:
            - 27003:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=pepper
            - MONGO_INITDB_ROOT_PASSWORD=pepper
    backend:
        build: ./backend
        ports:
            - 6587:6587
        depends_on:
            - database
    zorgmedewerker_app:
        build: ./zorgmedewerker-angular
        ports: 
            - 6588:6588
        depends_on:
            - backend
