version: '3.5'
services:
    database:
        image: mongo:4.4.5
        ports:
            - 27003:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=pepper
            - MONGO_INITDB_ROOT_PASSWORD=pepper
    # mosquitto:
    #     image: eclipse-mosquitto:2.0
    #     ports:
    #         - 1801:1883
    #     volumes:
    #         - ./mosquitto:/mosquitto/
    backend:
        build: ./backend
        # image: woutstev/pepper-zorg_backend:1.0
        ports:
            - 6587:6587
        environment:
            - MQTT_HOST=tcp://git.jijbentzacht.nl
            - MQTT_USERNAME=drpepper
            - MQTT_PASSWORD=securityBEtheKEY
            - MQTT_TOPIC=pepper-zorg-ti
            - SPRING_DATA_MONGODB_HOST=database
            - SPRING_DATA_MONGODB_PORT=27017
            - SPRING_DATA_MONGODB_USERNAME=pepper
            - SPRING_DATA_MONGODB_PASSWORD=pepper
            - ENCRYPTION_ENABLED=false
            - ENCRYPTION_PASSWORD=pepper
            - HTTP_USERNAME=pepper
            - HTTP_PASSWORD=pepper
        depends_on:
            - database
    # zorgmedewerker_app:
    #     build: ./zorgmedewerker-angular
    #     # image: woutstev/pepper-zorg_zorgmedewerker_app:1.0
    #     ports: 
    #         - 6588:6588
    #     depends_on:
    #         - backend
