server.port: 6587

mqtt:
  host: tcp://git.jijbentzacht.nl
  username: drpepper
  password: securityBEtheKEY
  topic: pepper-zorg-ti

spring.data.mongodb:
  host: database
  port: 27017
  database: pepper
  authentication-database: admin
  username: pepper
  password: pepper

encryption:
  enabled: true
  password: pepper
