server.port: 6587

mqtt:
  host: tcp://test.mosquitto.org:1883
  topic: pepper-zorg-ti

spring.data.mongodb:
  host: database
  port: 27017
  authentication-database: admin
  database: pepper
  username: pepper
  password: pepper

encryption.password: pepper
