package com.pepper.care.common

object CommonConstants {
    const val COMMON_PREFENCES: String = "COMMON_PREFENCES"

    const val COMMON_SHARED_PREF_LIVE_THEME_KEY = "PC_LT"
    const val COMMON_SHARED_PREF_PUBLISH_MSG_KEY = "PC_PM"

    const val COMMON_MSG_NAV_STANDBY= "PLATFORM:NAV:STANDBY"
    const val COMMON_MSG_NAV_INTRO= "PLATFORM:NAV:DIALOG*INTRO"
    const val COMMON_MSG_NAV_ID= "PLATFORM:NAV:DIALOG*ID"
    const val COMMON_MSG_NAV_PATIENT= "PLATFORM:NAV:DIALOG*PATIENT"
    const val COMMON_MSG_NAV_ORDER = "PLATFORM:NAV:ORDER"
    const val COMMON_MSG_NAV_MEDICATION= "PLATFORM:NAV:DIALOG*MEDICATION"
    const val COMMON_MSG_NAV_QUESTION = "PLATFORM:NAV:DIALOG*QUESTION"
    const val COMMON_MSG_NAV_FEEDBACK = "PLATFORM:NAV:FEEDBACK"
    const val COMMON_MSG_NAV_GOODBYE= "PLATFORM:NAV:DIALOG*GOODBYE"
}